name: Laravel App CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: bcmath, curl, gd, intl, mbstring, pdo_mysql, pdo_pgsql, zip, opcache

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Sync Project, Set Permissions, and Cache
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DEPLOY_DIR="/var/www/html/nttn-monitoring-application/test-backend"
            echo "Deploying Laravel app to $DEPLOY_DIR"

            rsync -a --delete --exclude '.env' ./ $DEPLOY_DIR/

            sudo chown -R www-data:www-data $DEPLOY_DIR
            sudo chmod -R 775 $DEPLOY_DIR/storage $DEPLOY_DIR/bootstrap/cache

            cd $DEPLOY_DIR
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

      - name: Restart Services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart php8.3-fpm
            sudo systemctl restart nginx
            sudo systemctl restart postgresql
            
            echo "Deployment completed successfully."
